# Generated by Django 5.1.4 on 2025-01-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Cooperation Letter', 'Cooperation Letter'), ('Employment Agreement', 'Employment Agreement'), ('Request/Sales Letter', 'Request/Sales Letter')], max_length=50)),
                ('document_status', models.CharField(choices=[('Sent for Signature', 'Sent for Signature'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('comments_notes', models.TextField()),
                ('expired_date', models.DateTimeField()),
                ('fullname', models.CharField(max_length=100)),
                ('document_number', models.CharField(max_length=20)),
                ('link_to_details', models.URLField()),
                ('link_to_document', models.URLField()),
            ],
        ),
    ]
