# Generated by Django 5.1.4 on 2025-01-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_document_delete_documentrequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='DocumentRequest',
        ),
    ]
