# Generated by Django 5.1.5 on 2025-01-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_document_documentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequest',
            name='comments_notes',
            field=models.TextField(default=''),
        ),
    ]
