# Generated by Django 5.1.4 on 2025-01-27 17:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_documentrequest_comments_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='account_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
