# Generated by Django 5.1.5 on 2025-01-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=100)),
                ('document_type', models.CharField(choices=[('Cooperation Letter', 'Cooperation Letter'), ('Employment Agreement', 'Employment Agreement'), ('Request/Sales Letter', 'Request/Sales Letter')], max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('comments_notes', models.TextField()),
                ('expired_date', models.DateTimeField()),
                ('document_number', models.CharField(max_length=20)),
                ('envelope_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='generatedlegaldocument',
            name='document_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
